import os
import argparse
from datetime import datetime

# ── Files and directories to always skip ──────────────────
SKIP_FILENAMES = {
    "manage.py",       # Django CLI boilerplate
    "wsgi.py",         # WSGI deployment interface
    "asgi.py",         # ASGI deployment interface
    "__init__.py",     # Empty namespace marker
    "export_source.py", # This script itself
}

SKIP_DIR_PARTS = {
    "migrations",      # Auto-generated by Django ORM
    "__pycache__",     # Compiled bytecode cache
    ".git",            # Version control internals
    "venv", ".venv",   # Virtual environment
    "node_modules",    # JS dependencies
    "staticfiles",     # Collected static files
}

def should_skip_file(rel_path: str, include_tests: bool) -> bool:
    parts = rel_path.replace("\\", "/").split("/")
    filename = parts[-1]

    if filename in SKIP_FILENAMES:
        return True

    for part in parts[:-1]:
        if part in SKIP_DIR_PARTS:
            return True

    if not include_tests and filename.startswith("test_"):
        return True

    return False

def collect_python_files(root: str, include_tests: bool) -> list[tuple[str, str]]:
    collected = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [
            d for d in sorted(dirnames)
            if d not in SKIP_DIR_PARTS
        ]
        for filename in sorted(filenames):
            if not filename.endswith(".py"):
                continue

            abs_path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(abs_path, root)

            if should_skip_file(rel_path, include_tests):
                continue

            collected.append((rel_path, abs_path))
    return sorted(collected, key=lambda x: x[0])

def build_header(rel_path: str, total: int, index: int) -> str:
    bar = "=" * 72
    return (
        f"\n{bar}\n"
        f"  [{index:02d}/{total:02d}]  {rel_path}\n"
        f"{bar}\n\n"
    )

def export(root: str, output_path: str, include_tests: bool) -> None:
    files = collect_python_files(root, include_tests)
    if not files:
        print("[export_source] No Python source files found.")
        return

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = len(files)

    with open(output_path, "w", encoding="utf-8") as out:
        out.write("=" * 72 + "\n")
        out.write("  視覺化網路攻擊自動化分析平台\n")
        out.write("  Network Attack Automated Analysis Platform\n")
        out.write(f"  Source Export — {timestamp}\n")
        out.write(f"  Total files : {total}\n")
        out.write("=" * 72 + "\n")
        out.write("\n[Table of Contents]\n")
        for i, (rel, _) in enumerate(files, 1):
            out.write(f"  {i:02d}. {rel}\n")
        out.write("\n")

        for i, (rel_path, abs_path) in enumerate(files, 1):
            out.write(build_header(rel_path, total, i))
            try:
                with open(abs_path, "r", encoding="utf-8") as src:
                    out.write(src.read())
                    out.write("\n")
            except Exception as e:
                out.write(f"# [ERROR] Could not read file: {e}\n")

    print(f"[export_source] Export complete: {output_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--out", default="source_code_export.txt")
    parser.add_argument("--include-tests", action="store_true", default=True) # 包含測試碼
    args = parser.parse_args()
    export(args.root, args.out, args.include_tests)
